"""
export_prompts.py
将所有 prompt variant 的最终渲染结果导出到 prompts/ 目录。

用法:
    python src/export_prompts.py            # 导出全部 7 个 variant
    python src/export_prompts.py --variant cot_full ab_no_s4

产物（每个 variant 两个文件）:
    prompts/{variant}/system_prompt.txt    完整 system prompt
    prompts/{variant}/user_message.txt     示例 user message（用演示对话）
    prompts/README.md                      各 variant 说明索引
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from prompt_builder import VARIANTS, build_prompt, list_variants

PROMPTS_DIR = Path(__file__).parent.parent / "prompts"

# 用于演示的固定样本（无需加载真实数据集）
_DEMO_SAMPLE = {
    "dial_id": "DEMO_001",
    "turn_id": 2,
    "history": [
        ("user",   "I'm looking for a cheap hotel in the east part of town."),
        ("system", "I found a few options. Do you have any other requirements?"),
        ("user",   "Yes, it needs free parking and free wifi. I'll be staying for 3 nights."),
    ],
    "belief": {
        "hotel-pricerange": "cheap",
        "hotel-area":       "east",
        "hotel-parking":    "yes",
        "hotel-internet":   "yes",
        "hotel-stay":       "3",
    },
}


def export_variant(variant: str) -> Path:
    """导出单个 variant，返回其子目录路径。"""
    cfg = VARIANTS[variant]
    out_dir = PROMPTS_DIR / variant
    out_dir.mkdir(parents=True, exist_ok=True)

    system_prompt, user_message = build_prompt(_DEMO_SAMPLE, variant=variant)

    # system_prompt.txt
    sys_path = out_dir / "system_prompt.txt"
    sys_path.write_text(system_prompt, encoding="utf-8")

    # user_message.txt（附带演示上下文说明）
    user_path = out_dir / "user_message.txt"
    header = (
        "# User Message Example\n"
        "# (Generated from a fixed demo dialogue for illustration)\n"
        "# --------------------------------------------------------\n\n"
    )
    user_path.write_text(header + user_message, encoding="utf-8")

    steps_str = " + ".join(s.upper() for s in cfg["steps"]) if cfg["steps"] else "—"
    print(f"  [{variant}]  system: {len(system_prompt):>5} chars  "
          f"| steps: {steps_str:<25} → {out_dir}")
    return out_dir


def export_readme(variants: list[str]) -> None:
    """生成 prompts/README.md 索引。"""
    lines = [
        "# Prompt Templates — Export Index\n",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
        "Each subdirectory contains the rendered prompt for one experimental variant.\n",
        "Files are generated by `src/export_prompts.py` and reflect the **current**",
        "state of `src/prompt_builder.py`. Re-run the script after any prompt edit.\n",
        "",
        "## Variants\n",
        "| Variant | Style | Steps included | Description |",
        "|---|---|---|---|",
    ]

    style_label = {
        "none": "No CoT",
        "fn":   "Schema-only (no CoT)",
        "free": "Free CoT",
        "structured": "Structured CoT",
    }
    for v in VARIANTS:
        if v not in variants:
            continue
        cfg = VARIANTS[v]
        steps_str = " + ".join(s.upper() for s in cfg["steps"]) if cfg["steps"] else "—"
        lines.append(
            f"| `{v}` | {style_label[cfg['style']]} | {steps_str} | {cfg['description']} |"
        )

    lines += [
        "",
        "## File Structure\n",
        "```",
        "prompts/",
        "├── README.md                    ← this file",
    ]
    for v in variants:
        lines.append(f"├── {v}/")
        lines.append("│   ├── system_prompt.txt        ← full system prompt")
        lines.append("│   └── user_message.txt         ← example user turn")
    lines.append("```")
    lines += [
        "",
        "## Demo Dialogue Used for `user_message.txt`\n",
        "```",
        "[turn 1] User: I'm looking for a cheap hotel in the east part of town.",
        "         System: I found a few options. Do you have any other requirements?",
        "[turn 2] User: Yes, it needs free parking and free wifi. I'll be staying for 3 nights.",
        "```",
        "",
        "Gold belief state:",
        "```json",
        '{"hotel-pricerange": "cheap", "hotel-area": "east",',
        ' "hotel-parking": "yes", "hotel-internet": "yes", "hotel-stay": "3"}',
        "```",
    ]

    readme_path = PROMPTS_DIR / "README.md"
    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n  README → {readme_path}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Export rendered prompts to prompts/ directory")
    ap.add_argument(
        "--variant", nargs="*", default=None,
        choices=list_variants(),
        help="导出指定 variant（默认全部）",
    )
    args = ap.parse_args()

    targets = args.variant if args.variant else list_variants()

    print(f"\nExporting {len(targets)} variant(s) to: {PROMPTS_DIR}\n")
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)

    for v in targets:
        export_variant(v)

    export_readme(targets)
    print(f"\nDone. {len(targets)} variant(s) exported.")


if __name__ == "__main__":
    main()
